---
apiVersion: networking.cfargotunnel.com/v1alpha1
kind: ClusterTunnel
metadata:
  name: talos-cluster-tunnel
spec:
  newTunnel:
    name: talos-tunnel         
  size: 2                      
  cloudflare:
    email: cloudflare.overflow261@simplelogin.com
    domain: mazilious.org         
    secret: cloudflare-secrets
    accountName: mazilious
    accountId: 

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-secrets
  namespace: cloudflare-operator-system
spec:
  encryptedData:
    CLOUDFLARE_API_KEY: AgBFXjLQ8Rlnr6dbjpC1ZP+589vGowqX6RsHRzz9jxeR9aLL6xE4kopSlRJgeRDjK9RnXYixGLCt+ANpxTMuFcJGf+DrMwBCgvA+wm4rVACgyhuNW8viOtO/khjhA8UWxh5atBoLoD8YOeQUZXDI4ormCg49A3r+h/66cZbYEYJnyzUjUWuAjmqmSDm9/LRh7rTamUmKU02ud+phKa+kLxJMnnLHpX5VSfguKfsMTVvUyKTCilW/PNj/WJwk7QSHHzyEK9u4zienZW0SzHLnG5p/RQLr4pW3wyPFZJQSF6jDD+vvOFSpN7Ccyk2zUcKPRyORW2QabnovfY0Tk4RvpcmP5VeoZtJsEtZt80T45e678JMv3iEj7xy00fom7XvnZmifdiLdKHaBqajqOVf5eAcZKbRt0ybVwy7EkMCAIFVUliheB/5SXw/TPRZF5udqVIOhKikH7fApQOMexmIQqnmhU0quDSz9iVCNYH+unHE/czvT2H0gThxt3zUEQSFKD6e4qSGNZmLMnMJRKpbThu3xWNKCupr4s0plmu/vzmlARtTWURAmJ3fLaAN45KGrTxehW8W2EEhroC+s9NwFg1TrZH9K/DRK93bKLoXFlYrUx949n7+IXAbVAPC2xIbmSyKbKYU8Mf7zEUGMr45pXUR8H3dE2z+N4Gly3W0g7fXJ50jtzVy4WfSIJLD4iGkizsf+3RhxUeLvM4R8GcVgTydqxXDke0jPIz7EfevHRJ+Z8y0ANJBr
    CLOUDFLARE_API_TOKEN: AgCi2pIsnhcugu5rLyEQgiwFcAG7Ajh0TruLslYF2umJtCYZkl9LJ+ksKcj4/5zWsjOWOdQN6tbMNX2CW70Kaw7PH4miyadVFkgAb2Zto6DAFrgcrzZ/vN2xw3w1OYK+P8ahnsxShbN6jbpqhmILyr5PMm59Czf72AqvRLPhmVUXfVkOHrmXVWgymVgfv3Iuqu/0V5QT6Ae7eR3QNeyHThkh7dYoszXPDPxwbUFh5IqskEPh9pGC1P+vkfGEQCqYOnzYzByK6bBOBOkDYLO1kuS64UqM6VF4jfHUVbHM8oOylRq/ZLUDnX9bUVua4pt6S6tQ5+uexQKHHUmGtnhi8bTAR58WpVtCH1UpTkod7Y6HbFJFQGj7cvfiLWxiU7CFUs2etwJNmfCQG3iTYgknQ4KnEjjte+LEbECXtenFj+Nq03XbZ7jzyQKZV8kqu9PRQ3/5av8njlcul8MwvjpbAsOCPB8mDFQaAFyFQZIrpJETDEpR7UN1QCAUDvtb8tcRILooP5Oy2xhaG5IYczuJx3svnWfuzOeg23foC2ICuAn1eIzDSW5XRlwEkm8v1/rBGnSaq11C7FmQlUcoRI6f0ukwrLWUNquKnOiPbbDelba4sPcz8w47oOQNnnpl4TI5UwxTdmY9nvYmJH2OPoTHsE6qwQKvvLMnQmAljV01U/nS8k5mqYoipkgyaUeQdAlETcwvB5q6g7NSv0DPCabwYYLPsl5EXokPP0X8jcbK5PDyPNKmW1+xkQxj
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-secrets
      namespace: cloudflare-operator-system
    type: Opaque
