---
apiVersion: networking.cfargotunnel.com/v1alpha1
kind: ClusterTunnel
metadata:
  name: talos-cluster-tunnel
spec:
  newTunnel:
    name: talos-tunnel         
  size: 2                      
  cloudflare:
    email: cloudflare.overflow261@simplelogin.com
    domain: mazilious.org         
    secret: cloudflare-secrets
    accountName: mazilious
    accountId: 179a8dec324d9cbb61bcbdb7542e9b75

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-secrets
  namespace: cloudflare-operator-system
spec:
  encryptedData:
    CLOUDFLARE_API_KEY: AgCNWfcIe/d4yj2cI4R6hReuDB/cwu78RD9gu0Bq5wC+HzpmogbczwS0GHIOV6LgzIpkTGCi3EcWkJu1lzXoTLNpREwH3zAKJp8n6QxoyT8J5cCVjgO4qvuYlZwbmXlJq0hy1uhPrJ2vXqYy38er8R07ZU776uY1bZd+Bl5Cb3mdNin2rOKJujinq4ICi8HfkN4YJ1Gu+46FeF7qRpnxyq6Lu7WUwz16z3Lndf8ImHWMi0l+MrvW98A53Ep1dTtNTYffEALCnQe5YtadwxPvkR8IWC+XzFL6iTirOyGY5eLL/Je0Kqq5indQJCsDq5JQwh2uTgIs4w8i8KfD9UBGNX1Hnaiqc/Bw4TtBvt3sT7Ov5kMKkWuK3MlIuCcv0OuYQEYVrl0IZAklSeJWEaz9HDOlrO38gL6RIUlX4VIyQ5H4tX+sUpcfLa234+I/DZBEdsRuraqpDggZRVHjKVixxIIdpRFAO0dCCQbykg9qj31G4GNnH7Vo9xFacVsBDFzHhPKc1Y4FpJHhrMdhz5B1LKIcpPXIxd8h7IyQQC8wOtxSvf8xSWRgBEqQDF7PHI1sJzZhG0gfsym/vVo/9/S5qJ1C9llPJFRGc2z/jOwaT0aQZnLXxAqUFVCvlVofd7pcmkWsJSyH+vqWrTe+65O/zExN3m7fL3wa+6fu1AWfR1r27NPWnItabZx9MDz91k/JIdGUYjrK7kAYi3pKcFB+++hwtyTnilQrAD4fEQ2niOqbtaV1JItp
    CLOUDFLARE_API_TOKEN: AgCpiTEZ3LguUo8FUx7Mxwbfk71INeRUvCUUePrDnkpisYofGP5r4iBFYmqyCyls+c14NxyiUFIIl/amGyXpisTnjn3vZYuXW2XjOVO4nU64V/2kvnMQxAJvaXh3M1xV5d6Bvxs+8bmTqbaf/xRu+1zeOtlNxiV/vrinr2sbmC27CTHy7Lt0Xh4trVx65uDCT1X4VFVdQh88mPZTsgJZ72sWKaNFTlPK8T6vqiZLRO1HRR3kygINqNObaKmbhvzszx7RIUbvSCU5Cf7FE/zfZeZQwvP0q3QQzt+DfBoJDD1g589Iew4qvEmVE5l+pQEXCBoingQKRqLKF+daZ5RzGiWl6956DdotAbjgGE3KpbbMy8VmXydU80qw7anc8E72/5OX0NKtLgNJMCNjsl3xZxSx78EEeTZLgSWMl/tXONydpXU0fAm4buKRZbIrtQ48K8Vdi5ZifWhkh3hCqMSjjxPHHdaOLvNH0X52JrocibVrK+sO6B+TouwdV9x49e8PAoXiRr5tTlV9GlJbpVs/OHKCWS/QoRiWGJ8mgakayrPntzVg3IRtWDP2OmAdmVrIMUxVDG/AYx1jY1UF3l4FjGoVSjbuJl+IckuKoIOxGoFDgDcIjPRCa6SLkuws4TEfJtHM2z5X055EBWscHyhXTaXfCR0+mfVO5Sa2ZeDGTWqHU4NQ8rIBzxQ+JAsaYwlMoPyXcWqsBe5Z52OQ+AZpHxZQsLBpBwSrdNtYLr1oEpgc5SnHzIE+ztgO
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-secrets
      namespace: cloudflare-operator-system
    type: Opaque
