---
apiVersion: networking.cfargotunnel.com/v1alpha1
kind: ClusterTunnel
metadata:
  name: talos-cluster-tunnel
spec:
  newTunnel:
    name: talos-tunnel         
  size: 2                      
  cloudflare:
    email: cloudflare.overflow261@simplelogin.com
    domain: mazilious.org         
    secret: cloudflare-secrets
    accountName: mazilious
    accountId: 

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-secrets
  namespace: cloudflare-operator-system
spec:
  encryptedData:
    CLOUDFLARE_API_KEY: AgB8dEjBu2P87VCQJ3/fgcm5wuP1eCcvU0MHRmGCYLcaPNN4yiytF61Zkg/Bm4UeK6DL4LZwAWe6TI+X6zYEG84lJwTR+XbLE7KYHyRMQLO4Ff3JwIv0XqVzJ1HhKBQksRpnsEyJEhleZ5j3MSpvpOUb1OQNYdiGDljsFjilLmwGeDSkFT4InjJIZpYIJoPZ8Ywuh9rhgsrmYXkaaBmc97m+NgPhdH8K+KMlUU6CUvtAzLIss2k5ZoTtRNIGdFCKCcAYLXEkCV8pof2BUeGxRttRqi8dzqVQP4LZnjssU86LEi9aPfmzNtwTYGZLRdY8/SKRsdLnzKeRJcAXgWB+BO2TR2ckWCm64TTjdk5Qq1Iihw3+qeMKwV/Vcy3ivjU+bUOCoDsO0UGGHAPYj93f5BfLYnAzAIP4iRXo3C9EAF0gowLm+9WChiFUzYtD6HMpwj7dtEqQr+6Q/oFEkO6H/n/AIU3gGId6EZP2s5zQN8z5RRPmOU7P26HBcQbNI76OXgdUJLBOVW/WN6Nk8DkZtjWpgOZlYY6Xd9ctYIlz9Kuqw4UXDMzMEevtbxrgb6F+Hf3pSpWTUeK+9DFglIkRigP7Ar8pi53xDi/vQizEwkwe/R8bUvDUxh1HXNqGVLYsJnq8D9N4Dhl676/El24WMwz4RNYWQrIEktScbWqIakc62J2hWTcOETYyK2J9eaJTcpDP1sNVernQ7o+dlO7AcobJJIj1V+s8Ivy3z3p0sWBP18GcrNijDQ==
    CLOUDFLARE_API_TOKEN: AgARLhgFvbs/ah/Flhpfh0CJ4NEdAcW1824gHyNp7fP3GU1cr0xfRH6rzh+CpQyZelJSSflTBs5/1WncVvVbsqQQKnns4mAm0qZOTLM6f2A/PzGc2Wy4BJ1qLFqRQmhKi65fgLerF/RvG+azirBSQkbveNBJv+Ts9npN/fSDF8Or9oy2yc+7VCJ779+PH3KBkMLz9pGb/kscwbgg8UsTQLs3v+Ls7syy2MDF+qj7EL/MPAWdMzz28SZOh/G3mS2Ufqp3HIbuEDK2AwnTFoPzT5H0X4jSxWw9w+Q0y142z+MgxKHGLSm+T5uGde4B8VeOlduYQ108tSRqCzSAGLT5HhyXdwkMUlt/45WoW1ssJ+0+OOb/YI4Ew8I+2X+xBkPcDvi5xeRAk+gO/W/ib6vaV9WdIE3bfxH1eQJZwtJp8A2ur9hnhAk+su+DSWwTaEsZgUoM3P8KKCEoOPtiFkONdb2BUg8UPQrwh6GXtg5jpOGNVW3FCMei7k4dFw0cVPwtJAQFKVeBaE1UFbll8cMhtBV54whwoNVCpr1rOEE9V5jyMjBVhpgZHFEZydy8/qsd7ipSe8+ONMQf4SUvAOgWDkfSLbzeAG5RjbnFS8Bp5m9AKNw/rLxDO8ZVNbO4lidCJMflfNjg/kLkAAwFLaa1asg6C/zObrBNvOINf66ryiVuQLzbkjDaIvtcJqbfQjLWZVHrbLMDRRs6XQgO5oW7evVDIeglmYdkyF5RGjG1IWLeCe2imgiM612YKA==
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-secrets
      namespace: cloudflare-operator-system
    type: Opaque
