project: default
source:
  repoURL: https://github.com/mfalicoff/gitops
  path: apps
  targetRevision: HEAD
  directory:
    recurse: true
    jsonnet: {}
destination:
  server: https://kubernetes.default.svc
  namespace: production
